### ISSUE TITLE
GraphQL subscriptions

### ISSUE THREAD

**Issue by aantron** [aantron/dream#26]
- [x] ~~[`Dream.graphql`](https://aantron.github.io/dream/#val-graphql) presently does not implement streaming responses at all, arguably a bug that should be addressed in the first or one of the first releases~~. These *are* subscriptions.
- [x] Implement GraphQL subscriptions using protocol [graphql-ws](https://github.com/enisdenjo/graphql-ws/blob/master/PROTOCOL.md#readme).

<br>

- [x] A subscriptions example, hyperlinked from [**`i-graphql`**](https://github.com/aantron/dream/tree/master/example/i-graphql#files) and the [API docs](https://aantron.github.io/dream/#graphql).
- [x] ~~Client verification for WebSocket upgrade GET requests~~. *Done by ordinary authentication checks, probably &mdash; there is no CSRF possibility with WebSockets AFAIK.*
- [x] Proper error messages sent back to the client.
- [x] Format of the variables JSON. Are enums possible? *Input coercion [here](https://atheros.ai/blog/how-to-use-graphql-enum-type-and-its-best-practices) suggests that they are represented as strings in JSON, so nothing needs to be done.*
- [x] In case of duplicate operation ids, should the connection be terminated, or should the existing id be replaced? [*The whole connection should be closed.*](https://github.com/enisdenjo/graphql-ws/blob/master/PROTOCOL.md#subscribe)
- [x] ~~Should more information be passed to the context-making function, in particular the operation name, variables map, and/or query itself?~~ *Separated out into #35.*
- [x] ~~Probably later, upon #12: be prepared to *stream* large responses. Might also need settings for incoming message size limits~~. *Moved to #12*.
- [x] Update docs.
- [x] Update GraphiQL to be compatible with this; default CDN distribution does not support subscriptions at all. See also #5, which can be solved concurrently.

<br>

Also:

- [x] ~~[Connection setup timeout](https://github.com/enisdenjo/graphql-ws/blob/master/PROTOCOL.md#connectioninit)~~. *This appears to be tied to the graphql-ws implementation. Hopefully it is prevented by authenticating GraphQL subscription requests. If not, it can easily be added later.*
